apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-loki-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: observability
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.9.10
    helm:
      values: |
        loki:
          config:
            auth_enabled: true
          persistence:
            enabled: true
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            size: 5Gi
          serviceMonitor:
            enabled: true

        promtail:
          enabled: true
          serviceMonitor:
            enabled: true

        grafana:
          enabled: true
          grafana.ini:
        server:
          root_url: https://grafana.local
        persistence:
          enabled: true
          type: pvc
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          size: 5Gi
          skipUpgrade: true
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - grafana.local
          path: /
          pathType: Prefix
          tls:
            - hosts:
                - grafana.local
              secretName: grafana-tls

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
