apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack-crds-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: observability
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/blurry-anya/self-hosting'
    targetRevision: main
    path: kustomizations/prometheus-stack-crds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - Prune=true