apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-aoa
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/blurry-anya/self-hosting'
    path: apps/infra
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true