apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-aoa
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: 'https://github.com/blurry-anya/self-hosting'
    path: apps/observe
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true